# Generated by Django 3.2.7 on 2021-10-23 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('junre', models.CharField(blank=True, max_length=20, null=True)),
                ('diff1', models.IntegerField(blank=True, default=0, null=True)),
                ('diff2', models.IntegerField(blank=True, default=0, null=True)),
                ('diff3', models.IntegerField(blank=True, default=0, null=True)),
                ('diff4', models.IntegerField(blank=True, default=0, null=True)),
                ('diff5', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='favorite_books',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='junres',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='readBooksModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughts', models.TextField()),
                ('value', models.IntegerField()),
                ('lower_diff', models.IntegerField()),
                ('upper_diff', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpost.bookmodels')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('to', models.IntegerField(blank=True, default=0, null=True)),
                ('good', models.IntegerField(blank=True, default=0, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpost.bookmodels')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpost.usermodel')),
            ],
        ),
    ]
