# Generated by Django 3.2.7 on 2021-10-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0004_alter_usermodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='junresModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junres', models.CharField(default='        django llvm agax        ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='languagesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='C C++ C# Python JavaScript', max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='junres',
        ),
        migrations.DeleteModel(
            name='languages',
        ),
    ]
