# Generated by Django 3.2.7 on 2021-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0007_auto_20211024_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='languages',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='ともや.JPG', upload_to=''),
        ),
    ]
