# Generated by Django 3.2.7 on 2021-10-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0008_auto_20211024_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodels',
            name='page',
        ),
        migrations.AddField(
            model_name='bookmodels',
            name='ibsn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
