# Generated by Django 3.2.7 on 2021-10-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0009_auto_20211025_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
