# Generated by Django 3.2.7 on 2021-10-25 06:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectpost', '0010_bookmodels_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookModels',
            new_name='bookModel',
        ),
        migrations.RenameModel(
            old_name='junresModels',
            new_name='junresModel',
        ),
        migrations.RenameModel(
            old_name='languagesModels',
            new_name='languagesModel',
        ),
        migrations.RenameModel(
            old_name='postModels',
            new_name='postModel',
        ),
        migrations.RenameModel(
            old_name='readBooksModels',
            new_name='readBooksModel',
        ),
    ]
