# Generated by Django 3.2.7 on 2021-10-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0013_alter_readbooksmodel_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbooksmodel',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
