# Generated by Django 3.2.7 on 2021-10-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0014_readbooksmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='ヒントからの最終盤面1.png', upload_to=''),
        ),
    ]
