# Generated by Django 3.2.7 on 2021-10-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0015_alter_usermodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readbooksmodel',
            old_name='order',
            new_name='order_junre',
        ),
        migrations.AddField(
            model_name='readbooksmodel',
            name='order_language',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
