# Generated by Django 3.2.7 on 2021-10-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0016_auto_20211026_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postBookOf', to='projectpost.bookmodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileOf', to='projectpost.usermodel'),
        ),
        migrations.AlterField(
            model_name='readbooksmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readBookOf', to='projectpost.bookmodel'),
        ),
        migrations.AlterField(
            model_name='readbooksmodel',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readerOf', to='projectpost.usermodel'),
        ),
    ]
