# Generated by Django 3.2.7 on 2021-10-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0017_auto_20211026_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='language_junre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
