# Generated by Django 3.2.7 on 2021-10-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpost', '0018_postmodel_language_junre'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=40, null=True)),
                ('question', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileOf', to='projectpost.usermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='postModel',
        ),
    ]
